-- Agregar campos faltantes a la tabla cursos
ALTER TABLE cursos 
ADD COLUMN IF NOT EXISTS bloques JSONB,
ADD COLUMN IF NOT EXISTS evaluaciones JSONB,
ADD COLUMN IF NOT EXISTS contenido TEXT,
ADD COLUMN IF NOT EXISTS prerequisitos TEXT,
ADD COLUMN IF NOT EXISTS certificado_template TEXT,
ADD COLUMN IF NOT EXISTS email_reporte TEXT,
ADD COLUMN IF NOT EXISTS clave_inscripcion TEXT,
ADD COLUMN IF NOT EXISTS precio DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
